### ISSUE TITLE
Plot Only Over The Most Recent Data

### ISSUE THREAD

**Issue by KeranYe** [tbattz/openGLPlotLive#2]
Hi,

First of all, I love this project!

My case is to run a soft real-time plot only over the most recent data (let us say 1000 time instances) and the previous portion should be dismissed. That is, the x-axis's origin tick number needs to increase once more than 1000 data points are received, yet keeping the x-axis span at 1000 time instances. 

I tested the "[examplePLot](https://github.com/tbattz/openGLPlotLive/blob/master/apps/examplePlot.cpp)"(Spring Damping Live Plot) and found that the x-axis's origin is fixed at zero as more data are received.

Any ideas?
Thanks

**Comment by tbattz** [comment]
No worries, happy that someone is getting some use out of it.

There's three ways to go about this. This first two are inefficient, but currently work, the third is probably the way it should be done, but is currently broken (as far as I can tell).

I've made a few changes and added an example to illustrate this. Those changes have been made in the "[movingTimeframe](https://github.com/tbattz/openGLPlotLive/tree/movingTimeframe)" branch, with some of the changes pulled into master. See [movingTimeframe.cpp](https://github.com/tbattz/openGLPlotLive/blob/movingTimeframe/apps/movingTimeframe.cpp) for details. Notably I've split the autoscaling of the x and y axes.

This also will depend on how much data and how quickly you're plotting it. What are you looking at using the plotter for? Currently due to the way openGLPlotLive stores data internally, it can start having a hard time if the length of the data gets too long (cpu usage rises over time). Though this was previously solved by option 3 (again, currently broken).

**Option 1 - Store entire time history, but only plot region of interest. Don't adjust y scale**
This is the first plot in the example file. Here you retain all the data, but manually adjust the x axes limits based on the last 1000 points.
https://github.com/tbattz/openGLPlotLive/blob/8db45367bc0d8c18a5d5f699e2abd28ee62b2f10/apps/movingTimeframe.cpp#L261-L268
Again, this will probably start falling over if you're adding a heap of points quite quickly, as it's storing the entire history. This leaves the y scaling to auto, meaning that the values are from the entire history of the plot.

**Option 2 - Store entire time history, but only plot region of interest, scaling y for the visible range**
This is effectively the same as option 1, but we grab the y values from the visible area, set y autoscale off, and manually set the y limits.
https://github.com/tbattz/openGLPlotLive/blob/8db45367bc0d8c18a5d5f699e2abd28ee62b2f10/apps/movingTimeframe.cpp#L271-L285
This has the same issue as option1.

**Option 3 - Circular Buffers**
When I first started writing this plotter, I had a similar use case to you, needing only the last few seconds of data, but for it to be updated quite quickly. Effectively needing a scrolling window. The remnats of this remain in me [iracingOverlay](https://github.com/tbattz/iracingOverlay) repo, with it only storing the last few seconds of data (which gets around the vectors becoming too long problem). The repo has moved on considerably from then, with it now being incompatible with the code from that time (back then it was just a simple graph, no axes, no buttons, no interaction e.t.c.). But, some of the files from there remain, notably the circular buffer line types, which I've been meaning to go back and re-integrate into the updated plotter, after I did a large overhaul of the internals. The [ShadedLine2D2CircularVecs.cpp](https://github.com/tbattz/openGLPlotLive/blob/master/src/shadedLines/ShadedLine2D2CircularVecs.cpp), made use of these circular buffers, but is currently implemented with expanding internal storage for the shaded line options, but retains most of the logic to make circular buffers work. So that might be your best starting point. [Line2D2CircularVecs.cpp](https://github.com/tbattz/openGLPlotLive/blob/master/src/lines/Line2D2CircularVecs.cpp) is effectively what you're after, but it hasn't been updated since the large overhaul of the internals (see it inheriting from ILine2_OLD rather than ISingleLine2D). 

I probably won't have the time in the near future to go and make the circular buffers work again (I may have a look but no promises). It might be as simple as linking it up to inherit from the new structure, and updating the updateInternalData(index) logic, following the pattern for the existing working classes ([Line2D2Vecs](https://github.com/tbattz/openGLPlotLive/blob/master/src/lines/Line2D2Vecs.h), [ShadedLine2D2CircularVecs](https://github.com/tbattz/openGLPlotLive/blob/master/src/shadedLines/ShadedLine2D2CircularVecs.h), [Scatter2D2Vecs](https://github.com/tbattz/openGLPlotLive/blob/master/src/scatterPlot/Scatter2D2Vecs.h)). You're free to give it a go to integrate the existing circular buffer files into the new structure, if you think you're up to it.


**Option 4 - Rewriting the entire vector**
This only came to mind while writing the other options, and may not work. It'll be inefficieint if it did work, but if you were to cap your input vector at 1000 entries, and effectively write to it as a circular buffer, writing back to the first index when it gets full, using the ShadedLine2D2CircularVecs file, you might be able to get it working by then calling updateInternalData(index), where index is your index for the oldest entry in the vector. This might force all the data to get updated at every step, instead of just the most recent data, which would be inefficient, but might work.

I hope that gives you something to try, that may get something useful working.

**Comment by KeranYe** [comment]
Thank you @tbattz

My case is to monitor multiple sensor data streaming at 100Hz to 1kHz, though I tend to limit the plotting rate to 100Hz cause my eyes won't tell the difference between 100Hz and something higher. 

Your suggestion is very helpful. I guess the core step is to adjust the x-axis limits for every plotting step, regardless of the vector size, which should be fine to me by now.

I did my own change to the examplePlot: popping up the first element of the data vectors with std::vector::erase() while back-pushing a new one. I notice that std::vector::erase() is not efficient and std::deque::erase() is more efficient at erasing the front element() yet it may still not solve the size growing issue. Do you think it is reasonable to include std::deque as an alternative to std::vector as the data buffer?

Below is my code (only the loop plotting part of the examplePlot.cpp) and at least it works at the moment.

        /* ======================================================
	 *                     Drawing Loop
	   ====================================================== */
	float i = 0;

	// Game Loop
	while(!glfwWindowShouldClose(window->getWindow())) {

		// Pre-loop draw
		window2->preLoopDraw(true);

        // Keran: data truncation
        const size_t max_data_count = 1000;

		// Update Plot Data
        // Update graph 12
        // Keran: truncate vector if full 
        if( line12b->dataPtX->size() >= max_data_count )
        {
            line12b->dataPtX->erase( line12b->dataPtX->begin() );
            line12b->dataPtY->erase( line12b->dataPtY->begin() );
        }
        line12b->dataPtX->push_back(i);
        yVal12 = cos((i) / (25*M_PI)) * exp(-(i)/(25*8*M_PI));
        line12b->dataPtY->push_back(yVal12);
        line12b->updateInternalData();

        // Update graph 13
        if( line13b->dataPtX->size() >= max_data_count )
        {
            line13b->dataPtX->erase( line13b->dataPtX->begin() );
            line13b->dataPtY->erase( line13b->dataPtY->begin() );
        }
        line13b-> dataPtX->push_back(i);
        yVal13 = cos((i) / (2*25*M_PI)) * exp(-(i)/(25*8*0.5*M_PI));
        line13b->dataPtY->push_back(yVal13);
        line13b->updateInternalData();

        // Update Graph 15
        if( line15b->dataPtX->size() >= max_data_count )
        {
            line15b->dataPtX->erase( line15b->dataPtX->begin() );
            line15b->dataPtY->erase( line15b->dataPtY->begin() );
        }
        line15b->dataPtX->push_back(i);
        yVal15 = exp(-(i)/(25*8*M_PI));
        line15b->dataPtY->push_back(yVal15);
        line15b->updateInternalData();

        // Update Graph 16
        if( line16b->dataPtX->size() >= max_data_count )
        {
            line16b->dataPtX->erase( line16b->dataPtX->begin() );
            line16b->dataPtY->erase( line16b->dataPtY->begin() );
        }
        line16b->dataPtX->push_back(i);
        yVal16 = -exp(-(i)/(25*8*M_PI));
        line16b->dataPtY->push_back(yVal16);
        line16b->updateInternalData();

        i += 1;

        float xmin = line12b->dataPtX->front();
        float xmax = line12b->dataPtX->back();
        axesPt->setXAxesLimits(xmin, xmax);

		// Draw Plot
		myplot->Draw();



		// For Debugging
		//myplot->drawBoundingBox();
		//myplot->drawMouseOverBox();
        //std::shared_ptr<GLPL::Axes> axesPt = myplot->getAxes(0);
        //axesPt->setPosition(axesPt->getLeft() + 0.001, axesPt->getBottom() - 0.001);


		// Post-loop draw
		window2->postLoopDraw();

	}

**Comment by tbattz** [comment]
No worries @KeranYe.

Since the last big overhaul of the code, the plotter became more useable, but less efficient underneath. So hopefully it holds up under that data streaming rate. I've been meaning to go back through and make a few changes for efficiency, but haven't got around to it. 

Popping and erasing the first/last elements of the vector seems to have made a difference for the vector expanding issue.

Deque might be the way to go, though you'll get the speedup when you receive the data, you might see a slowdown internally within the plotter. Currently the plotter reproduces the data it is given internally, so that it has the correct structure to pass into the OpenGL buffers, and onto the GPU. In the initial code a few years back, I had imagine it (and partially had it working), to take in a pointer to the data and feed that straight to the GPU. This caused a bunch of issues and crashes, relied on the user to not do silly things, and forced the user to use a certain structure for their data. This is why I moved towards copying the data internally and resconstructing it in a format more friendly for the GPU, but this will have made the code more inefficient (both in terms of performance and memory requirements). So while the speedup with deque will be seen on the user side, it "might" be slower when the updateInternalData function runs, and it needs to dereference each value twice, instead of once for a vector. I might be wrong (I kinda hope I'm wrong actually as deque would be quite convienient to use if it works), but we won't find out unless it gets tried out. Below is the updateInternalData function for the line plotter.

https://github.com/tbattz/openGLPlotLive/blob/09bb5a592654b30e7c62c4ccf30490d93b9632f2/src/lines/Line2D2Vecs.cpp#L36-L73

If you wanted to give it a try, it probably wouldn't be too much effort to make a version of [Line2D2Vecs](https://github.com/tbattz/openGLPlotLive/blob/master/src/lines/Line2D2Vecs.h) that takes deques instead of vectors, for the internalData and internalIndicies. There'd be a few changes in updateInternalData required, but I think most of it would be a one to one drop in. Though as the number of points stops changing, that logic might need altering to add a flag to tell the plotter that the data has changed.

**Comment by KeranYe** [comment]
Agree. I will probably try it out with deque in the future. For now, I am pretty happy with the setup. Cheers~
